#!/bin/sh
while read file
do
    case "$1" in
        "d")
            gio trash "$file";;
	"r")
            convert -rotate 90 "$file" "$file" ;;
	"R")
            convert -rotate -90 "$file" "$file" ;;
	"|")
            convert -flop "$file" "$file" ;;
	"y")
            echo -n "$file" | xclip -selection clipboard &&
                notify-send "$file copied to clipboard" & ;;
	"Y")
            readlink -f "$file" | xclip -selection clipboard &&
                notify-send "$(readlink -f "$file") copied to clipboard" & ;;
        "w")
            feh -B"#000000" --bg-fill "$file" && mv ~/.fehbg ~/.cache/fehbg ;;
        esac
done
